name = "mist"
version = "5.0.0"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }
target = "erlang"
gleam = ">= 1.10.0"

[dependencies]
gleam_erlang = "1.0.0-rc1"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_otp = "1.0.0-rc2"
gleam_stdlib = ">= 0.50.0 and < 1.0.0"
hpack_erl = "~> 0.3"
logging = "~> 1.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gramps = ">= 3.0.0 and < 4.0.0"
glisten = ">= 8.0.0 and < 9.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.2"
