name = "mist"
version = "0.2.1"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }

[dependencies]
gleam_stdlib = "~> 0.21"
gleam_erlang = "~> 0.9"
gleam_http = "~> 3.0"
gleam_otp = "~> 0.4"
glisten = "~> 0.3"
# glisten = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.6"
