name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "25.3"
          gleam-version: "0.27.0"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
